### ISSUE TITLE
How to use this tool

### ISSUE THREAD

**Issue by PranamyaJake** [edgi-govdata-archiving/web-monitoring#147]
Hi, I am a newbie, as i was exploring this tool, i couldn't understand how to use this tool(i hv already read README file). Can someone please help me how to use the tool or code base , or can i get any documents or link where i can read about it

**Comment by Mr0grog** [comment]
Are you trying to access the service that is live, or are you trying to set up your own copy?

**Comment by PranamyaJake** [comment]
I am trying to set up my own copy

**Comment by Mr0grog** [comment]
Since it’s built as a suite of small services, you’ll need to set up instances of web-monitoring-db, web-monitoring-processing, and web-monioring-ui, then give them addresses to each other in their configuration so they can communicate (see the sample environment files in each project). Then you can start importing data by posting to the `/api/v0/imports` endpoint on web-monitoring-db.

Hopefully the [`ARCHITECTURE.md` doc](https://github.com/edgi-govdata-archiving/web-monitoring/blob/master/ARCHITECTURE.md) might give you a good sense of how the different pieces fit.

**Comment by Mr0grog** [comment]
(Also, if you want to deploy with Kubernetes, you can take a look at how we have things set up in the web-monitoring-ops repo.)
