### ISSUE TITLE
Comments on Trello board: EDGI: Web Monitoring Project - Onboarding 

### ISSUE THREAD

**Issue by KrzysztofMadejski** [edgi-govdata-archiving/web-monitoring#44]
Ping @patcon 
- [x] [Test-drive the chatbot](https://trello.com/c/tYe3Q31B/19-test-drive-the-chatbot) card is empty. What is chatbot? Where to find it? How to test it? 

- [x] https://trello.com/c/zG8OiKiw/14-perform-your-first-code-review
  - doesn't have any description
  - doesn't it require some experience, trust and being promoted to a Lieutenant?

- [x] https://trello.com/c/D8YpNQgR/15-request-write-access-to-the-repo
  - same as above

- [x] https://trello.com/c/jLXvgHUb/7-review-the-ui-demo-video the video https://www.youtube.com/watch?v=MG5UOZ6Ck1E ping @lightandluck 
  - could use a [link to heroku](http://web-monitoring-gapi.herokuapp.com/) in the description
  - TODO it's not clear where to get spreadsheet links

- [ ] https://trello.com/c/ZoaSMbpy/8-explore-the-live-app 
  - there is nothing the explore :|
  - most of the links connect to Versionista, but it asks for login
  - even if I create an account I don't have acces to those views ("This page was not found. Perhaps it was deleted?")

- [ ] I'd copy Analyst-focused onboarding tasks in a separate onboarding process for analysts (or does it exist alread?). I'd put/link it in [How to help? Readme section](https://github.com/edgi-govdata-archiving/web-monitoring#how-to-help):
  - https://trello.com/c/jLXvgHUb/7-review-the-ui-demo-video (for me it's too complicated as for self-onbiarding developer at this stage; first time I see this I)
  - https://trello.com/c/ZoaSMbpy/8-explore-the-live-app 

- [ ] Split [How to help? Readme section](https://github.com/edgi-govdata-archiving/web-monitoring#how-to-help) in two:
 - Become an Analyst
 - Join web development team

- [ ] I'd link [Trello onboarding](https://trello.com/b/FCGGEaQq/edgi-web-monitoring-project-onboarding) in [How to help? Readme section](https://github.com/edgi-govdata-archiving/web-monitoring#how-to-help) section (developer part)

**Comment by KrzysztofMadejski** [comment]
https://trello.com/c/yRMYHQie/13-get-memberized-on-our-github-teams has a task `Consider setting your new memberships to "Public" (See "People" tab on org profile) -- Hooray for future job interview cred!` @b5 @titaniumbones you're set to private on https://github.com/orgs/archivers-space/people ;-)

**Comment by patcon** [comment]
Oh! Sorry, this is great feedback, @KrzysztofMadejski. Unfortunatlely, I wasn't advertising the board after our sprint, so it wasn't quite ready for usage yet. So I'm truly sorry for any time I caused you to waste. But again, you comments seem REALLY helpful

It seems I need the equivalent of a "master"/"develop" branch on Trello, as some of these cards we stubs so that I didn't forget to add content later...! But that def shouldn't happen when people are actively depending on it.

From now on, I will work on another board and transfer cards to that one only when complete :+1:

**Comment by patcon** [comment]
For now, I'm going to clearly mark the incomplete cards (to avoid taking anyone else's time for granted), and I'll flesh them out asap.

**Comment by patcon** [comment]
> * https://trello.com/c/jLXvgHUb/7-review-the-ui-demo-video the video https://www.youtube.com/watch?v=MG5UOZ6Ck1E ping @lightandluck
>
>   * ~could use a link to heroku in the description~
>   * TODO it's not clear where to get spreadsheet links

@lightandluck what's your suggestion here? I'm unclear on the flow :)

1. Are the sample spreadsheets still appropriate to use?
  * If so, can we add back auto-filled defaults like we used to have?
2. Is this video still a resource you'd recommend onboarding with?
3. Should we bother to address where the _actual_ URLs will come from? (or even just hint that "how to get them" will be better addressed in the 50-minutes analyst training video?)

**Comment by lightandluck** [comment]
> 1. Are the sample spreadsheets still appropriate to use?

No, we shouldn't be focusing on the spreadsheets anymore. The gapi app was meant to be a transitional prototype to be on parity with the analyst workflow. We were hoping to get some use and feedback but after speaking with the admin team, they would like v0 to be more fleshed out before trying to switch people over. Namely, having comparable diff services to remove the need for linking out to versionista.  

> 2. Is this video still a resource you'd recommend onboarding with? 

No, the video was only meant to show analyst quickly how to use the gapi app. Both the app and video should be deprecated and not used for onboarding. We should focus on the React app. 

> 3. Should we bother to address where the actual URLs will come from? 

For the UI, all data is coming from web-monitoring-db: urls, annotations, diffs, etc. And we can certainly address that. Anyone interested should go to [staging](https://web-monitoring-db-staging.herokuapp.com/) and play with the API. Now, how the DB gets all that data is a better question for Mr0grog. 

We should remember that even though web-monitoring is split into different projects, they are meant to work together as a single app. The UI is just a thin layer to work with the DB in a user-friendly way. DB and processing are the most important parts and understanding that relationship helps think about the project. 

**IMHO, Understanding the data coming from DB, how to get it and what it represents should be the focus of onboarding.** As far as I'm concerned, even the current UI could be thrown away right now if there was a better replacement and I'd welcome that wholeheartedly.

> Any thoughts on how we could make this a better experience?

Unfortunately, we can't give everyone access to Versionista because of reasons of privacy and money. I think the best way to get a good sense of the why and how of web-monitoring would be the first 20ish minutes of the [dev onboarding video](https://www.youtube.com/watch?v=zaGeNEyMULE) which is a really good overview. Then the 50min analyst video (sorry I don't have a link), which breaks down the current analyst process. Then, whether the person was more interested in DB or UI, they could either watch the rest of the dev onboarding except last 20ish minutes of Q&A or the UI+Analyst meeting ([part1](https://www.youtube.com/watch?v=5zMY-ZAmJ7E&feature=youtu.be), [part2](https://www.youtube.com/watch?v=iXcjTH4X-_0&feature=youtu.be)). (Honestly I recommend both.)

The analyst meeting will probably grow stale over the next couple months because we're talking about just immediate problems which hopefully will be solved soon. It's not comprehensive, but  gives a good sense of current needs. The dev onboarding should be more evergreen barring some monumental change.

**Comment by patcon** [comment]
Thanks @lightandluck! The last 2 paragraphs will be particularly helpful. I'll mine this for next steps tomorrow

(I just added your helpful summary from before as a TOC in the [dev onboarding video](https://www.youtube.com/watch?v=ig8rjII0wkU) description, so also belated thanks for that)
