### ISSUE TITLE
Move all-contributors to this overview repo

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/web-monitoring#71]
Slack context: https://archivers.slack.com/archives/C47DJK8H0/p1506368023000634

If we could get Rebeccca Lave and analysts into [the `web-monitoring-db` contributors table](https://github.com/edgi-govdata-archiving/web-monitoring-db/#contributors), would it make sense to move that to this repo instead of the specific code repos?

Also, does it make sense to recognize analyst work here? Maybe it doesn't.

Project repo: https://github.com/kentcdodds/all-contributors
Issue to add new category to recognize data/content contributions: https://github.com/kentcdodds/all-contributors/issues/63

**Comment by Mr0grog** [comment]
So, to be clear:

1. Move contributor recognition out of each code repo and into this overview repo instead and
2. Add people contributing to the analysis work instead of the the software-related work to the contributors list?

I’m fine with that if others would like to do so and if analysts want to be listed here.

Personally, I feel ambivalent about whether we should try and scope the list of contributors here to only those working on the software or everyone working on EDGI’s monitoring project (we have sort of the opposite issue [on the website](https://envirodatagov.org/website-monitoring/monitoring-team/), where there is an incomplete list of software folks, at least as compared to the contributor list here). I think there are reasonable arguments on either side (e.g. clarity of purpose vs. meaningful recognition vs. is the work here about being part of the analyst work or about creating a software service) and I don’t personally have a horse in that race.

**Comment by lightandluck** [comment]
Fixed in #78
