### ISSUE TITLE
Create folder and migrate meeting notes to a more accessible place

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring#99]
After losing (temporary?) access to hackmd, let's create a folder in this repo and store meeting notes.
Use IPFS as a reference.
https://github.com/ipfs/pm/tree/master/meeting-notes

Or could also go in google drive:
https://drive.google.com/drive/u/0/folders/1yd-jrVLiCLLz1URSHVRCf2XcCypHZXa4

**Comment by patcon** [comment]
Was just looking for this as a place to store notes from our quick and casual meeting this morning :)

When we do have a place, perhaps we could link it prominently from the README?

A nice-to-have feature of whatever we choose: ability for the listing of notes to be public, but the private meetings to have access control :)

**Comment by Mr0grog** [comment]
I like the idea of keeping them in-band by having them in the repo here, but…

We’ve already got meetings notes for the last few months in a Google Drive folder that is publicly accessible (so long as we are happy sharing the link). Just sharing that link might be simplest and probably best.

Otherwise, I say a system like IPFS’s seems to work alright, though it has slightly more overhead: do collaborative notes for a meeting in HackMD (same as we used to) and the note-taker is responsible for making a PR to enshrine the final notes in a git repo after the meeting. That cuts out Hackfoldr from the workflow, which I think was the main thing that was buggy and error-prone before. (It makes more sense to me to do Hackfoldr + Git than GDocs/Drive + Git because 1) plain text is more compatible with Git and 2) there’s no confusion about where/how things are *organized* [drive vs. Git repo])

**Comment by patcon** [comment]
:+1: to GDrive

Note: the link shared above is not public (required access request), and even with access, it's just an empty "Admin" folder. Maybe we meant this one? https://drive.google.com/drive/u/0/folders/0BxkWFSoyVYI3YVZXY1JxVllFVkU

**Comment by Mr0grog** [comment]
I was intentionally *not* posting the link, because nobody’s talked about whether it should be public!

**Comment by lightandluck** [comment]
Thanks for the concern @Mr0grog! 

I think Gdrive is best right now too and it's ok to make the meeting notes folder public. WM meetings are open to anyone. I know the Trello board is currently private which is bad, but realize it's because it's mixed with EDGI-only meetings, so we're gonna have to re-think that again. 

It didn't cross my mind before when I made it, sorry! But then again, Hackfoldr was only "private" through obscurity. So, Rob's right, we never came to a resolution on how this should all be organized. 😳

I'll bring this up at All-EDGI meeting and with DT folks and see if we can agree to something that makes sense.

**Comment by weatherpattern** [comment]
Quick update. FWIW, I've copy all the web mon dev meeting notes from hackmd to gdrive, so it's all in one place.

If we add the gdrive link to the repo, the setting should be those with the link can comment, but not edit. I believe this allows people with the link to add comments and also suggestions, which can be approved by someone with admin permissions.

@Mr0grog: "It makes more sense to me to do Hackfoldr + Git than GDocs/Drive + Git":
Did you mean Hackfoldr or HackMD?
I thought we agreed at the big tools meeting to move off of Hackfoldr and onto Trello.

**Comment by Mr0grog** [comment]
> Did you mean Hackfoldr or HackMD?

Sorry, HackMD.

**Comment by Mr0grog** [comment]
> If we add the gdrive link to the repo, the setting should be those with the link can comment, but not edit.

I think the doc should be openly editable until the meeting it covers ends. But after that, yes, we don’t want them to be editable.

**Comment by patcon** [comment]
> I think the doc should be openly editable until the meeting it covers ends.

To minimize admin, what about this one-time process:
- [x] Create a template for meetings. [example](https://docs.google.com/document/d/1q4QTrymCd9CbX2_EDsZcVxknAZFGHWC-bv94a32q-6s/edit#)
    - [x] Link to template in the template itself (so anyone creating an agenda can intuit the process)
    - [x] Add a call-out box explaining to anyone reading how they can contribute (I feel new attendees will appreciate this being explicit :) ) -- text itself is totally your call
    - [x] Set the permissions on the template to "comment" (gdrive folders can only be set to "view" or "edit", not "comment" -- contained files created from scratch will only be either "view" or "edit", but copying from template means it starts as "comment", so less tedium to remember for agenda-creator)

So now, when creating a new template, we just go to template (following link from any existing set of notes), and click `File > Make a copy...`

Would that be helpful? I feel like the "edit" vs "comment" toggling before and after meetings could be avoided, so long as people know that suggestions are welcome. If ppl submit an edit, we can just make a point to give them full gdrive access going forward -- no changes will happen from newcomers without it being evident via suggestion mode

**Comment by patcon** [comment]
And templates prevent format drift, even when hosted by different ppl -- changes to template can be encouraged by intentional, possibly via suggestion :)

**Comment by Mr0grog** [comment]
I guess my concerns around permissions are more that having to suggest and get approved is a pretty high bar pre-meeting. It can work; I just feel like it adds a lot of friction especially if the person who has to accept might not be present (e.g. if @weatherpattern made the doc but then wasn’t able to make the meeting, so someone else needed to manage the doc at that point).

**Comment by patcon** [comment]
I know there were some other discussions, but for now, will this close out this issue?
https://github.com/edgi-govdata-archiving/web-monitoring/pull/100

**Comment by lightandluck** [comment]
Yea, I think so. If we revisit how we do this, we can create a new issue.
